# Vitenskapsfilosofi

## Induksjon

Innenfor vitenskapsfilosofi er induksjon «en vitenskapelig metode som på grunnlag av enkelte, individuelle utsagn eller erfaringer søker å komme frem til mer omfattende generelle utsagn eller lover» [@tranøy2021]. En skeptiker av denne metoden var David Hume. Hume argumenterte med at det ofte ble brukt induksjon for å trekke generelle slutninger basert på tidligere erfaringer [@dybvig2019] Humes skepsis til induksjon blir ofte kalt induksjonsproblemet [@holmen2023]. Dette er knyttet til at premisser og argumenter ofte kan være sanne uten at konklusjonen nødvendigvis må være sann. Et induktivt argument kunne vært at solen kom opp i morges, solen kom opp i går, solen kom opp dagen før i går. Dermed vil solen komme opp i morgen. Hume mente at vi ikke kan rasjonelt begrunne vår tro på at fremtiden vil ligne fortiden. Det vil derfor ikke nødvendigvis være noen forbindelse mellom tidligere hendelser og fremtidige hendelser, og at selv om solen har stått opp hver dag så lenge man kan huske er det ikke gitt at den vil stå opp en million år. Hume mente dermed at alle påstander om fremtiden (inkludert påstander om hva som sannsynligvis vil skje), forutsetter at man antar at fremtiden vil ligne på fortiden, og at dette er en antagelse som ikke kan begrunnes. Hume argumenterte også med at det ikke er mulig å gi en rasjonell begrunnelse for bruk av induksjon uten å anta det en prøver å bevise -- at naturen vil være uniform i fremtiden. Det vil dermed ikke være mulig å bevise induksjonens gyldighet uten å bruke induksjon. Et annet argument Hume brukte var at menneskers tro på kausalitet -- en grunnleggende faktor for induksjon - er basert på en vane, og ikke en nødvendig forbindelse. Om man ser at en hendelse følger en annen, antar man kausalitet. Dette er ifølge Hume ikke en logisk begrunnelse for å anta at årsak og virkning alltid vil være forbundet. Flere har presentert «løsninger» til induksjonsproblemet. Karl Popper forkastet induktive slutninger med begrunnelsen om at det ikke var «logisk mulig å slutte seg fra enkeltobservasjoner til allmenne lover på en logisk gyldig måte» [@dybvig2019]. Popper mente at vitenskapen ikke hadde noe behov for å rettferdiggjøre bruken av induksjon. Nelson Goodman lanserte det nye induksjonsproblemet i et forsøk på å analysere Humes induksjonsproblem. Goodman mente at svaret på Humes induksjonsproblem var at «induktive slutninger har en egen form for gyldighet som gjør noen av dem legitime. Det vi må gjøre er derfor å definere eller skille ut hvilke slutninger som er induktivt gyldige fra de som ikke er det» [@holmen2023]. Goodman mente at oppgaven kan ikke løses ved å «henvis til formallogiske eller syntaktiske trekk ved induktive slutninger. Konsekvensen av dette er at det ikke er mulig å gi et formallogisk system for induktive slutningsformer». Jeg vil ikke si at hverken Popper eller Goodman sine «løsninger» løser induksjonsproblemet, de prøver heller i en grad å unngå bruken av induksjon. Jeg tror induksjonsproblemet teknisk sett ikke kan løses. Hume kommer med gode argumenter som underbygger problemet med bruken av induksjon og mangelen på logikk ved bruken av den. Jeg mener at det derimot fortsatt er en plass til induksjon i vitenskapen, så lenge det blir brukt på riktig måte. Induksjon er en effektiv metode å benytte seg av og det blir allerede benyttet mye både i vitenskapen og i hverdagen. Skal man tenke at solen kanskje ikke står opp i morgen fordi naturen ikke er uniform vil man låse seg helt til Humes tankegang. Man må rett og slett heller bare akseptere at induksjon er en metode som som regel er bra nok.

## Falsifikasjonisme

Falsifikasjonisme er en filosofi som ble utviklet av Karl Popper. Den går ut på at det er umulig å verifisere en hypotese helt og holdent, man kan selv ikke si at en hypotese sannsynligvis er sann (uansett hvor mye vi vet), men at vi kan forsøke å falsifisere den [@dybvig2019]. Det er ifølge Popper falsifiserbarheten som skiller vitenskap fra pseudovitenskap eller ikke-vitenskapelige påstander, og han mente at dersom en hypotese var falsifiserbar var den vitenskapelig. Vitenskapen er ikke i stand til å bevise en teori eller en hypotese som sann, eller sannsynligvis sann, men den kan falsifisere teorier som ikke stemmer. Dette gjør at vitenskapelige teorier forbedres ved å erstatte gamle teorier som har blitt bevist feil. Falsifikasjonisme forutsetter at hypotesen dreier seg om noe generelt. Et klassisk eksempel på falsifikasjonisme som også Popper brukte er teorien om at alle svaner er hvite. Dette er en generell påstand om fargen til svaner. Denne teorien må ifølge falsifikasjonismen kunne være falsifiserbar dersom den skal være vitenskapelig. Er det dermed slik at hvis en observerer 1000 hvite svaner har verifisert teorien? Nei, for det er nemlig ingenting som tilsier at ikke en svart svane plutselig kan dukke opp et sted i verden. Dersom en observerer en svart svane er teorien bevist feil, men inntil da kan den ikke bevises at den er riktig. Problemet med falsifikasjonisme er at det er vanskelig å avgjøre når en teori er falsifisert. Dersom en person lanserer en teori kan denne ofte tilpasses eller beskyttes mot falsifisering ved å benytte seg av. Studien ville da blitt klassifisert som pseudovitenskap. Tilpasninger av en studie kan for eksempel argumenteres med at falsifiseringen skyldes feil i eksperimentet eller andre variabler som påvirker resultatet. Vitenskapelige teorier er ofte komplekse og kan dermed være vanskelig å falsifisere. Problemet med falsifikasjon kan løses til en viss grad, men det avhenger av teorien som skal falsifiseres. Teorien om at alle svaner er hvite er lite kompleks, og er enkel å falsifisere. En dokumentert observasjon av en svart svane er alt som skal til for å falsifisere teorien. En teori som er vanskeligere å falsifisere er teorien om at global oppvarming påvirkes av mennesker. Det er mye som tyder på at denne teorien stemmer, men dette er ikke et bevis for at den er sann eller verifisert. Det er derimot vanskelig å avvise teorien. Det er mange faktorer som er involvert i global oppvarming, og det er dermed ikke mulig med en enkel test eller en observasjon for å komme frem til et endelig svar på dette. Ved komplekse teorier som er vanskelig å falsifisere kan en helhetlig vurdering gjøre forståelsen i det vitenskapelige miljøet bedre. Vitenskap er sjelden «enten eller», og temaet global oppvarming finnes det mye forskning på. Denne forskningen kan dermed brukes til å si at global oppvarming sannsynligvis er påvirket av mennesker. Å bruke absolutte begreper som verifisert og falsifisert er sjeldent enkelt, da for mange faktorer kan påvirke forskjellige studier.
